### ISSUE TITLE
Create notes folder if it does not excists

### ISSUE THREAD

**Issue by mhoek2** [mhoek2/pycalculator#11]
Based on this suggestion https://github.com/mhoek2/pycalculator/issues/8#issuecomment-2360923186

It is a good idea to implement creating the 'notes' folder if it does not excist on the host system

**Comment by mhoek2** [comment]
@nidunc  Zou je kunnen checken of die nu de map 'notes' aanmaakt?

**Comment by nidunc** [comment]
De rekenmachine crasht nu niet meer als de `notes` map niet bestaat en maakt ’m aan, dus het lijkt nu goed te werken.

**Comment by mhoek2** [comment]
Thanks voor de bevestiging, deze issue kan worden gesloten
