### ISSUE TITLE
Tekst loopt over

### ISSUE THREAD

**Issue by nidunc** [mhoek2/pycalculator#13]
Als je meer tekst invoert in het invoerveld dan wat er inpast, dan loopt de tekst over naar de ruimte rechts van het veld (en buiten het zichtbare gedeelte van de rekenmachine).
Ik zou alleen niet gelijk weten wat hier de beste oplossing voor is. Een aantal opties:
- De tekst op één regel houden, maar de lettergrootte kleiner maken naarmate er meer tekst in het invoerveld komt,
  - Niet echt ideaal, gezien de tekst op deze manier op den duur wel héél klein kan worden;
- Alle tekst die overloopt op een nieuwe regel plaatsen (en dus het invoerveld hoger maken),
  - Dit kan weer problemen geven met de uitlijning van alle andere elementen van de rekenmachine (het is ook weer niet de bedoeling dat de berekening over het resultaat, of zelfs de knoppen, heen gaat, bijvoorbeeld). In dit geval zullen meerdere dingen dan ook dynamischer / meer in _real-time_ berekend moeten worden (voor zover dat nu niet al gedaan wordt);
- De rekenmachine _resizable_ maken (handmatig dan wel automatisch), zodat je alsnog kan zien wat er ingevoerd is door de rekenmachine in de breedte groter te maken,
  - Het venster kan natuurlijk alleen maar zo breed gemaakt worden als de breedte van het scherm waarop het zich bevindt, dus mogelijk zou dit met een van de vorige twee opties gecombineerd moeten worden.

Wat denk(en) j(ulli)e dat de beste oplossing is?
(Overigens heeft iets als dit natuurlijk niet de hoogste prioriteit, gezien dit in principe ook maar een simpele rekenmachine hoeft te zijn, maar het kan de UX wel verbeteren.)

**Comment by mhoek2** [comment]
@nidunc 

Goede stelling.

Font size aanpassen vindt ik wel een prima idee.

Wat mij opvalt aan andere calculators is dat ze ook de tekst kleiner maken.

Windows calculator:
Invoer begint rechts (onze links) Zo is altijd wat je typt in focus.
Een maximum invoer accepteren, totdat er een modifier als ```["+", "-", "x", ":"]``` wordt gebruikt.
Dan wordt de vorige invoer of uitkomst verplaatst naar een regel erboven.

Google calculator:
Invoer begint rechts (onze links) Zo is altijd wat je typt in focus.
Berekening verdwijnt links uit beeld.

**Comment by nidunc** [comment]
(Nog een mogelijke optie: een scrollbalk toevoegen aan het invoerveld als deze overloopt, om horizontaal te scrollen. Al ziet dat er wel wat lelijk uit, dus een andere oplossing heeft waarschijnlijk sowieso de voorkeur.)

**Comment by nidunc** [comment]
> Invoer begint rechts (onze links) Zo is altijd wat je typt in focus.

Dit lijkt me ook wel goed om te implementeren.

**Comment by mhoek2** [comment]
Dat kan, ik weet niet of dat lukt in de huidige tijdsplan.

Op dit moment het invoerveld enkel  een witte rectangle met op dezelfde coordinaten een soort print van de equation : string

**Comment by mhoek2** [comment]
Ik toegevoegd dat de font kleiner wordt en dat de tekst rechts uitlijnt.

Ik dank dat dit voor het doeleind van dit project voldoende is, mocht dit later nog een probleem worden.
Dan kunnen we er dan nog naar kijken.
