### ISSUE TITLE
Notitie functie

### ISSUE THREAD

**Issue by nidunc** [mhoek2/pycalculator#15]
Op dit moment wordt een notitie (in principe) succesvol opgeslagen in een tekstbestand, maar er wordt nergens aangegeven wat de lengte van de ingevoerde tekst is (wat natuurlijk wel een doel was van deze functie). Wellicht kan er nog een functie worden toegevoegd die de lengte van de tekst onder het invoerveld weergeeft (eventueel in _real-time_)?

- [x] Lengte van tekst weergeven in UI

En de bestandsnaam van notities begint nu met `note_%d_%m_%Y`, waar in principe niet heel veel mis mee is, maar in dit soort situaties kan het handiger zijn om `note_%Y_%m_%d` te hanteren (ongeveer zoals [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) het doet); dan worden de notities ook altijd in de goede volgorde van oud naar nieuw weergegeven in bestandsverkenners en dergelijke, zonder dat je hoeft te sorteren op de datums van de bestanden.
En wellicht kan de lengte van de notitie dan ook in de bestandsnaam gezet worden.

- [x] Schrijfwijze van datum veranderen in bestandsnaam _(niet essentieel)_
- [x] Lengte van notitie toevoegen aan bestandsnaam _(niet essentieel)_

(Eventueel kan ik die laatste twee zelf wel oppakken.)

**Comment by mhoek2** [comment]
Het punt ```Lengte van tekst weergeven in UI``` is gedaan.  (722b5dbb6009e4a15cdabfb728e2ffbc12752edc)

Ik vindt het prima hoor als je het format wilt veranderen :)

Die code vindt je hier:
https://github.com/mhoek2/pycalculator/blob/722b5dbb6009e4a15cdabfb728e2ffbc12752edc/modules/notes.py#L29

**Comment by nidunc** [comment]
@mhoek2 Vanwaar eigenlijk deze regel?
https://github.com/mhoek2/pycalculator/blob/890a5a71153570d7054e2ea3f92ec326e4d6c924/modules/gui/gui.py#L350

Is dat om te voorkomen dat er meer tekst wordt ingevoerd dan in het invoerveld past?

**Comment by mhoek2** [comment]
> @mhoek2 Vanwaar eigenlijk deze regel?
> 
> https://github.com/mhoek2/pycalculator/blob/890a5a71153570d7054e2ea3f92ec326e4d6c924/modules/gui/gui.py#L350
> 
> Is dat om te voorkomen dat er meer tekst wordt ingevoerd dan in het invoerveld past?

Correct, dit is het maximum aantal characters dat mag worden ingevoerd bij notities.
Dit in combinatie met realtime counter rechts onder het invoerveld, kan je zien hoeveel letters je hebt gebruikt van het maximum toegestane aantal.

![image](https://github.com/user-attachments/assets/d635fbb7-4f95-4bf5-965e-247403e577aa)
