### ISSUE TITLE
Refactor duplicate in the GUI

### ISSUE THREAD

**Issue by mhoek2** [mhoek2/pycalculator#18]
@nidunc 

Ik heb wat code gevonden waar te weinig verschil in zit om telkens te dupliceren.

Ik heb dit in een nieuwe branch aangepast, omdat dit meer een cosmetic is dan een bug or feature.

Zie: https://github.com/mhoek2/pycalculator/commit/89f33cc21620f1fb2f6b0c21092172818ff9f076

Mocht je dit alsnog gemerged willen hebben laat het dan even weten.

**Comment by nidunc** [comment]
Ik had in eerste instantie simpelweg wat code gekopieerd en aangepast en had het nog niet geoptimaliseerd, maar zo is het inderdaad wel beter, dus voel je vrij om het te mergen.

**Comment by nidunc** [comment]
(Overigens is de code waar dit op gebaseerd is nog wel van vóór de commit waarin ik de conversie-functies echt heb gefixt—toen de functies nog omgedraaid waren—dus dat moet nog worden aangepast.)

**Comment by mhoek2** [comment]
Ja ik kwam er achter nadat ik pull request had aangemaakt :D
