### ISSUE TITLE
Probleem met shortcuts

### ISSUE THREAD

**Issue by nidunc** [mhoek2/pycalculator#9]
Dit werkt niet helemaal goed als iemand tekst aan het invoeren is bij Notities: https://github.com/mhoek2/pycalculator/blob/211e923c6e9ca96c1eae71460864034f7d3038b3/modules/gui/gui.py#L168-L177

Als je een van de letters in deze functie intoetst, gaat de rekenmachine naar het desbetreffende tabblad, in plaats van de letter in het tekstveld in te voeren. Willen we daar nog een ‘modifier’ bij doen (zoals <kbd>Alt</kbd>+<kbd>c</kbd> in plaats van alleen maar <kbd>c</kbd>), of is deze functie niet echt meer nodig?

**Comment by mhoek2** [comment]
Dit heb ik toegevoegd als debug code toen er nog geen tabbladen waren.
Dus deze hele code kan wel weg, pak ik wel even op.
Goed opgemerkt!

**Comment by mhoek2** [comment]
Opgelost in deze commit: adc7a3eb24c4868668b9d4e0c0f979fcce1b352e

**Comment by mhoek2** [comment]
@nidunc  Zou je kunnen checken of dit nu is opgelost?

**Comment by nidunc** [comment]
> @nidunc Zou je kunnen checken of dit nu is opgelost?

’k Heb even getest met `qwertyuiopasdfghjklzxcvbnm`, en de focus bleef de hele tijd op het notities tabblad, dus het is inderdaad opgelost.
